[
    {
        "id":3,
        "username":"jose1",
        "password":"$2b$10$Na2mIv0UzV4gUvU6ipNvtO/XHJW3bTBPM63h6ocV9/E1E07Zb/chi",
        "email":"josefina@mail.com",
        "last_name":null,
        "first_name":null,
        "phone":null,
        "address":null,
        "city_state_zip":null,
        "carts":[
            {
                "id":5,
                "user_id":3,
                "product_id":2,
                "quantity":1
            },
            {
                "id":6,
                "user_id":3,
                "product_id":3,
                "quantity":1
            }
        ],
        "products":[
            {"id":2,"product_name":"T-Shirt","description":"Professional T-shirt","price":"10","stock":50,"category_id":2,"cart":{"id":5,"user_id":3,"product_id":2,"quantity":1}},{"id":3,"product_name":"Football boots","description":"Professional boots","price":"100","stock":50,"category_id":3,"cart":{"id":6,"user_id":3,"product_id":3,"quantity":1}}]}]